# Generated by Django 5.2.13 on 2026-05-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rfq_base_status_rfq_alter_archivo_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq_assignment',
            name='winning_supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
