# Generated by Django 5.2.13 on 2026-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rfq_assignment_winning_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mold_costbr_p2_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mold_costbr_p3_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mold_costbr_p4_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mold_costbr_p5_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
