# Generated by Django 5.2.14 on 2026-05-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_suppliers_alter_die_trim_i_id_rfq_and_more'),
        ('api', '0005_mold_costbr_p2_s_elaborated_by_and_more'),
    ]

    operations = [
    ]
