# Generated by Django 5.2.14 on 2026-05-21 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_merge_20260518_2200"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mold_costbr_p2_s",
            name="Elaborated_by",
        ),
        migrations.RemoveField(
            model_name="mold_costbr_p3_s",
            name="Elaborated_by",
        ),
        migrations.RemoveField(
            model_name="mold_costbr_p4_s",
            name="Elaborated_by",
        ),
        migrations.RemoveField(
            model_name="mold_costbr_p5_s",
            name="Elaborated_by",
        ),
        migrations.RemoveField(
            model_name="rfq_assignment",
            name="winning_supplier",
        ),
        migrations.AddField(
            model_name="rfq_assignment",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="status_rfq",
            name="lev9",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RFQ_Tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_alcanzado", models.CharField(max_length=10)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "id_rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to="api.rfq_base",
                    ),
                ),
                (
                    "usuario_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RFQ_Tracking",
            },
        ),
    ]
