# Generated by Django 5.2.15 on 2026-06-04 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_fix_die_nullable_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_costbr_p1_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_costbr_p2_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_costbr_p3_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_costbr_p4_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_trim_i_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_trim_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_cavities_p1_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_cavities_p1_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_cavities_p2_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_cavities_p2_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_cavities_p3_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_cavities_p3_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_costbr_p1_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p2_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_costbr_p2_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p3_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_costbr_p3_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p4_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_costbr_p4_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p5_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_costbr_p5_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_info_p1_i_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_info_p1_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_info_p2_i_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_info_p2_s_supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
