# Generated by Django 5.2.15 on 2026-06-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_die_costbr_p1_s_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Admi_resid_burr_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Bisc_Pos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Ejec_syst_fix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Gas_Sprin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Gros_wei_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Introduc_Extract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Max_wall_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Min_wall_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='No_cavities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='No_hydr_slid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Part_dimen_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Part_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Press_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Projec_area_cm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Quant_punch_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Surf_cm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Temp_trim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_i',
            name='Volu_cm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='AirDevi_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='AirDevi_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='AirDevi_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='AirDevi_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Base_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Exchange_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Last_edit_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='Max_Weight_trim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='MerkCyl_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='MerkCyl_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='MerkCyl_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='MerkCyl_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthAccCst_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthAccCst_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthAccCst_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthAccCst_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthMat_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthMat_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthMat_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='OthMat_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='RawMat_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='RawMat_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='RawMat_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='RawMat_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='SensIFM_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='SensIFM_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='SensIFM_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='SensIFM_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TeleLimit_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TeleLimit_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TeleLimit_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TeleLimit_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalAccCst_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalAccCst_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalAccCst_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalAccCst_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalMatCost_PriceUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalMatCost_Total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalMatCost_Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p1_s',
            name='TotalMatCost_Weeks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Assem_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Assem_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Assem_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Assem_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Drill_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Drill_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Drill_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Drill_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='EDM_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='EDM_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='EDM_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='EDM_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Grind_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Grind_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Grind_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Grind_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Mill_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Mill_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Mill_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Mill_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthMachin_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthMachin_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthMachin_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthMachin_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthManual_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthManual_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthManual_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='OthManual_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Spot_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Spot_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Spot_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Spot_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='StripPolish_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='StripPolish_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='StripPolish_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='StripPolish_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalMachinCst_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalMachinCst_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalMachinCst_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalMachinCst_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalManuWk_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalManuWk_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalManuWk_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='TotalManuWk_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Turn_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Turn_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Turn_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Turn_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Wirecut_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Wirecut_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Wirecut_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p2_s',
            name='Wirecut_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Adjust_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Adjust_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Adjust_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Adjust_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='CamNC_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='CamNC_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='CamNC_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='CamNC_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Coat_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Coat_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Coat_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Coat_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Desig_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Desig_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Desig_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Desig_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='GrTotalTrimAdjust_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='GrTotalTrimAdjust_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='GrTotalTrimAdjust_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='GrTotalTrimAdjust_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Grain_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Grain_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Grain_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Grain_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Hard_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Hard_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Hard_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Hard_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Nitri_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Nitri_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Nitri_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='Nitri_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthEngDesign_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthEngDesign_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthEngDesign_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthEngDesign_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthHeatSurf_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthHeatSurf_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthHeatSurf_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthHeatSurf_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthTrimDie_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthTrimDie_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthTrimDie_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='OthTrimDie_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalHeatSurf_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalHeatSurf_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalHeatSurf_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalHeatSurf_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalManufCst_H',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalManufCst_PriceH',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalManufCst_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p3_s',
            name='TotalManufCst_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='CleaningPack_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='CleaningPack_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='CleaningPack_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='CleaningPack_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DieImprovements_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DieImprovements_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DieImprovements_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DieImprovements_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DutyCosts_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DutyCosts_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DutyCosts_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='DutyCosts_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='GrTotalSparePt_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='GrTotalSparePt_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='GrTotalSparePt_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='GrTotalSparePt_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthSparePt_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthSparePt_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthSparePt_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthSparePt_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthersLogistics_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthersLogistics_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthersLogistics_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='OthersLogistics_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='SparePt_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='SparePt_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='SparePt_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='SparePt_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalLogistics_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalLogistics_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalLogistics_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalLogistics_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalToolReplace_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalToolReplace_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalToolReplace_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TotalToolReplace_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportBTCtoSupp_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportBTCtoSupp_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportBTCtoSupp_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportBTCtoSupp_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportSuppToBTC_PriceUnit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportSuppToBTC_Total',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportSuppToBTC_Unit',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_costbr_p4_s',
            name='TransportSuppToBTC_Weeks',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Adjust_opt_tool_maker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Admissible_res_burr_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='CUST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Castings_supp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='DESC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='DTQB',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Deli_date_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Desi_2D_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Desi_3D_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Ejec_syst_fix_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Frame_Refur_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Ful_Auto_proc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Gas_spri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Hydra_Cylin_switch_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Late_trim_imp_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Manu_Propo_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='No_cavities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='No_hydra_slides',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Others_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='PPY',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='PROJ_L',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='PT_No',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Presence_Detec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Press',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Pun_pins_req',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Punch_Data_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Set_elec_wires_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Set_spare_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Sketch_die_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Trim_No_1_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Trim_No_2_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_i',
            name='Trim_proc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Acc_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Acc_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Acc_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Acc_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Adjus_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Adjus_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Adjus_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Adjus_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='DATE',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='GrTotal_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='GrTotal_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='GrTotal_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='GrTotal_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Logis_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Logis_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Logis_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='Logis_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='ManuCst_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='ManuCst_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='ManuCst_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='ManuCst_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='MatCst_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='MatCst_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='MatCst_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='MatCst_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='SpParts_TD1_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='SpParts_TD1_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='SpParts_TD2_PrBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='die_trim_s',
            name='SpParts_TD2_TmBd',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Alloy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Buhler_Machine_Ton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Gross_weight_in_g',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Max_wall_thickness_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Min_wall_thickness_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Number_of_cavities_sets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Number_of_gates_per_part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Number_of_hydr_slides',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Number_of_mech_slides',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Number_of_parts_per_stroke',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Number_of_tools',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Part_dimension_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Part_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Projected_area_in_cm2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Surface_in_cm2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Three_plate_mold',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_i',
            name='Volume_in_cm3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Base_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Last_edited_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_dimensions_Ejector_Side_1_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_dimensions_Ejector_Side_2_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_dimensions_Ejector_Side_3_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_dimensions_Fixed_Side_1_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_dimensions_Fixed_Side_2_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_dimensions_Fixed_Side_3_in_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_weight_Ejector_Side_in_kg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p1_s',
            name='Tool_weight_Fixed_Side_in_kg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p2_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p3_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p4_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_costbr_p5_s',
            name='Elaborated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='CMGOM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='CUST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='ChillBl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='DESC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='ELAB',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='HICS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='Ihtcs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='Jco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='NReturnV',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='No_CAV',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='No_PlJcosys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='No_ofHS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='No_ofMS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='No_subc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='Oth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='PNUM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='PRLF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='PT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='QcSys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='SPforThermoR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='Smach',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='Spin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='TT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='ThirdPSupp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_i',
            name='VacV',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p1_s',
            name='Curr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Add_of_mach_st_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='CMM_dim_rep_cai_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Comp_D_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Dim_corr_opt_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Eyeb_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='FICF_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='FlAn_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Fr_Refur_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='GOM_rep_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='HCLS_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='H_val_subc_in_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Ldi_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='ManProp_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='OW_Conn_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Run_and_over_mod_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Run_des_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='STM_1_2_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Set_of_repl_H13_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Sketch_d_conc_inc_s_dim_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Sp_Pt_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Sp_set_of_EI_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='Subseq_D_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='ThreeDDModSolid_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='ThreeD_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_i',
            name='TwoDDrDes_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='Comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='INC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='PREP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='QT_No',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='SIGN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mold_info_p2_s',
            name='SUPP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
