# Generated by Django 5.2.14 on 2026-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_die_costbr_i_admi_resid_burr_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='die_trim_i',
            name='comodity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='die_trim_i',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='die_trim_i',
            name='part_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='die_trim_i',
            name='part_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='die_trim_i',
            name='part_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='die_trim_i',
            name='part_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='die_trim_i',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='comodity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='part_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='part_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='part_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='part_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mold_info_p1_i',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rfq_base',
            name='ia_predictions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
