name: tc3005b-bocar
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - django
      - djangorestframework
      - django-cors-headers
      - djangorestframework-simplejwt
      - dj-rest-auth
      - python-dotenv
      - psycopg2-binary
      - pillow
      - django-filter
      - pandas
      - numpy
      - openpyxl
      - xlrd
      - matplotlib
      - seaborn
      - plotly
      - requests
      - django-extensions
      - ipython
      - gunicorn
      - pytest
      - pytest-django